---

kind: pipeline
name: default
type: docker

platform:
  arch: amd64
  os: linux

steps:

  - name: test
    image: docker.pkg.github.com/vegaprotocol/devops-infra/cipipeline:1.11.13
    pull: always
    volumes:
      - name: gocache
        path: /go/cache
      - name: gopkg
        path: /go/pkg
    environment:
      CGO_ENABLED: "0"
      GO111MODULE: "on"
      GOARCH: amd64
      GOCACHE: /go/cache
      GOOS: linux
    commands:
      - make retest

  - name: coverage
    image: docker.pkg.github.com/vegaprotocol/devops-infra/cipipeline:1.11.13
    volumes:
      - name: gocache
        path: /go/cache
      - name: gopkg
        path: /go/pkg
    environment:
      CGO_ENABLED: "0"
      GO111MODULE: "on"
      GOARCH: amd64
      GOCACHE: /go/cache
      GOOS: linux
    commands:
      - make coveragehtml
    when:
      ref:
        - refs/heads/master
        - refs/heads/develop

volumes:
  - name: gocache
    host:
      path: /var/lib/drone/volumes/quant/gocache
  - name: gopkg
    host:
      path: /var/lib/drone/volumes/quant/gopkg

image_pull_secrets:
  - dockerconfig
