---
image: registry.gitlab.com/vega-protocol/devops-infra/cipipeline:1.11.5

variables:
  CGO_ENABLED: "0"
  GO111MODULE: "on"
  GOOS: linux
  GOARCH: amd64
  GOPATH: "${CI_PROJECT_DIR}/go"  # Can only cache files inside ${CI_PROJECT_DIR}
  # There's no recursive expansion of vars.
  BIN_DIR: "${CI_PROJECT_DIR}/go/bin"
  SRC_DIR: "${CI_PROJECT_DIR}/go/src"
  PKGMOD_DIR: "${CI_PROJECT_DIR}/go/pkg/mod"

cache:
  key: ${CI_COMMIT_REF_SLUG}  # one cache per branch
  paths:
    - ${PKGMOD_DIR}

stages:
  - test

before_script:
  - mkdir -p "${BIN_DIR}" "${PKGMOD_DIR}" "${SRC_DIR}"
  - for d in ${PKGMOD_DIR} ; do echo "There are $(find "$d" | wc -l) files/dirs in $d" ; done
  - find -maxdepth 1 -not -name . -and -not -name go -exec mv '{}' "${SRC_DIR}/" ';'
  - cd "${SRC_DIR}" || exit 1

after_script:
  - cd "${CI_PROJECT_DIR}" || exit 1
  - find "${SRC_DIR}" -maxdepth 1 -not -name src -exec mv '{}' ./ ';'
  - rmdir "${SRC_DIR}"
  - for d in ${PKGMOD_DIR} ; do echo "There are $(find "$d" | wc -l) files/dirs in $d" ; done

unit_tests:
  stage: test
  script:
    - make test

code_coverage:
  stage: test
  script:
    - make coveragehtml
  only:
    - /^(master|develop)$/
